exports.tryCatch = (controller) => async (req, res, next) => {
    try {
        await controller(req, res);
    } catch (error) {
        console.log("ðŸš€ ~ file: tryCatch.js ~ line 5 ~ exports.tryCatch= ~ error", error)
        return next(error);
    }
};
